version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-empacotamento
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: empacotamento_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: app-empacotamento
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/empacotamento_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppassword
      SPRING_FLYWAY_URL: jdbc:mysql://mysql:3306/empacotamento_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_FLYWAY_USER: appuser
      SPRING_FLYWAY_PASSWORD: apppassword
    restart: unless-stopped

volumes:
  mysql_data: